# Generated by Django 2.2.6 on 2021-10-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20211017_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=1, verbose_name='Название поста'),
            preserve_default=False,
        ),
    ]
